version: '3.4'
services:
  db:
    image: docker.io/postgres:latest
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - '5432:5432'
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data
      - ./database/scripts/create.sql:/docker-entrypoint-initdb.d/init.sql
